---
- name: Deploy war file to servers
  hosts: all
  become: yes

  tasks:
    - name: Install Tomcat9
      apt:
        name: tomcat9
        state: present

    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
    - name: Create project05 directory
      file:
        path: "/var/lib/tomcat9/webapps/ROOT/project05"
        state: directory
        recurse: yes
    - name: Copy file
      copy:
        src: "webapp/target/webapp.war"
        dest: "/var/lib/tomcat9/webapps/ROOT/project05"
    - name: Unpack war file
      unarchive: src=/var/lib/tomcat9/webapps/ROOT/project05/webapp.war dest=/var/lib/tomcat9/webapps/ROOT/project05 copy=no mode=0755
