---
- name: Deploy war file to servers
  hosts: all
  become: yes
  env:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - name: Create project05 directory
      file:
        path: "/opt/tomcat/latest/webapps/project05"
        state: directory
        recurse: yes
    - name: Copy file
      copy:
        src: "webapp/target/webapp.war"
        dest: "/opt/tomcat/latest/webapps/project05"
    - name: Unpack war file
      unarchive: src=/opt/tomcat/latest/webapps/project05/webapp.war dest=/opt/tomcat/latest/webapps/project05 copy=no mode=0755
